#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: The MK Blog
# Short bio or description (displayed in the header)
description: This is my online blog about random things in my daily life. There is no telling what my next post might include, as my mind tends to wander very precariously throughout the day.

#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
git branch -m main primary
git fetch origin
git branch -u origin/primary primary
git remote set-head origin -a
